// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_first_steps = "CgkIvZyg6bMXEAIQAQ"; // <GPGSID>
        public const string achievement_cube_master = "CgkIvZyg6bMXEAIQBQ"; // <GPGSID>
        public const string achievement_getting_better = "CgkIvZyg6bMXEAIQAw"; // <GPGSID>
        public const string achievement_addicted = "CgkIvZyg6bMXEAIQBA"; // <GPGSID>
        public const string achievement_escaped = "CgkIvZyg6bMXEAIQBw"; // <GPGSID>
        public const string achievement_not_bad = "CgkIvZyg6bMXEAIQBg"; // <GPGSID>
        public const string leaderboard_highscores = "CgkIvZyg6bMXEAIQAg"; // <GPGSID>
        public const string achievement_unstoppable = "CgkIvZyg6bMXEAIQCA"; // <GPGSID>

}

